package API.ConnetionManager;
import javax.net.ssl.*;
import java.security.cert.X509Certificate;
import java.security.SecureRandom;
public class SslConfigurator {


    /**
     *
     * @return returns trust manager for certification of request
     * @author - generated by Gemini AI
     */
        public static SSLSocketFactory sslFalseCertif() {
            try {
                TrustManager[] trustAllCerts = new TrustManager[]{
                        new X509TrustManager() {
                            public X509Certificate[] getAcceptedIssuers() { return null; }
                            public void checkClientTrusted(X509Certificate[] certs, String authType) {}
                            public void checkServerTrusted(X509Certificate[] certs, String authType) {}
                        }
                };

                SSLContext sslContext = SSLContext.getInstance("TLS");
                sslContext.init(null, trustAllCerts, new SecureRandom());

                return sslContext.getSocketFactory();

            } catch (Exception e) {
                throw new RuntimeException("Creating trust manager failed...", e);
            }
        }

}
